CONTRACTION_PHONEMES = {
    "i'm": {"src": "aɪ|'|ɛ|m", "dst": "aɪ|m"},
    "they're": {"src": "ð|eɪ|'|ɹ|iː", "dst": "ð|eɪ|ɹ"},
    "won't": {"src": "w|ʌ|n|'|t|iː", "dst": "w|oʊ|n|t"},
    "can't": {"src": "k|æ|n|'|t|iː", "dst": "k|æ|n|t"},
    "don't": {"src": "d|ɑː|n|'|t|iː", "dst": "d|oʊ|n|t"},
    "you're": {"src": "j|uː|'|ɹ|iː", "dst": "j|ʊ|ɹ"},
    "we're": {"src": "w|iː|'|ɹ|iː", "dst": "w|ɪ|ɹ"},
    "i'll": {"src": "aɪ|'|ɛ|l|ɛ|l", "dst": "aɪ|l"},
    "he's": {"src": "h|iː|'|ɛ|s", "dst": "h|iː|z"},
    "she's": {"src": "ʃ|iː|'|ɛ|s", "dst": "ʃ|iː|z"},
    "it's": {"src": "ɪ|t|'|ɛ|s", "dst": "ɪ|t|s"},
    "we'll": {"src": "w|iː|'|ɛ|l|ɛ|l", "dst": "w|iː|l"},
    "they'll": {"src": "ð|eɪ|'|ɛ|l|ɛ|l", "dst": "ð|eɪ|l"},
    "i've": {"src": "aɪ|'|v|iː", "dst": "aɪ|v"},
    "you've": {"src": "j|uː|'|v|iː", "dst": "j|uː|v"},
    "we've": {"src": "w|iː|'|v|iː", "dst": "w|iː|v"},
    "they've": {"src": "ð|eɪ|'|v|iː", "dst": "ð|eɪ|v"},
    "i'd": {"src": "aɪ|'|d|iː", "dst": "aɪ|d"},
    "you'd": {"src": "j|uː|'|d|iː", "dst": "j|uː|d"},
    "he'd": {"src": "h|iː|'|d|iː", "dst": "h|iː|d"},
    "she'd": {"src": "ʃ|iː|'|d|iː", "dst": "ʃ|iː|d"},
    "we'd": {"src": "w|iː|'|d|iː", "dst": "w|iː|d"},
    "they'd": {"src": "ð|eɪ|'|d|iː", "dst": "ð|eɪ|d"},
    "you'll": {"src": "j|uː|'|ɛ|l|ɛ|l", "dst": "j|uː|l"},
    "that's": {"src": "ð|æ|t|'|ɛ|s", "dst": "ð|æ|t|s"},
    "tulu": {"src": "tʃ|ə|l|uː", "dst": "t|uː|l|uː"},
    "what's": {"src": "w|ʌ|t|'|ɛ|s", "dst": "w|ʌ|t|s"},
    "aren't": {"src": "æ|ɹ|ə|n|'|t|iː", "dst": "ɑː|ɹ|n|t"},
    # ... 可扩展更多缩写词
} 